### ISSUE TITLE
Not your plugin

### ISSUE THREAD

**Issue by ArchonKlaus** [AL3XPI/CompassMCPE-plugin#1]
Please, change the author of the plugin because it is not yours. Original repo: https://github.com/nitf/ViewCompass

**Comment by AL3XPI** [comment]
What? I coded this plugin dude

**Comment by ArchonKlaus** [comment]
No. You just copied from that plugin. You released this today and that repo 9 month ago, the code and the functions are the same. You copied it, give the right credits.

**Comment by AL3XPI** [comment]
No, I did not copy it. This is such a simple plugin that there is only few ways to make it. Coincidentally, my plugin is similar to his.

**Comment by ArchonKlaus** [comment]
No no. The Main is the same, the Task is the same, It is copied. I will close this issue but just change author name. Goodbye

**Comment by AL3XPI** [comment]
I didn't even know that repository existed.

**Comment by AL3XPI** [comment]
But for the sake of your and my sanity, I guess I'll close the repository.
